# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ajaya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ajaya/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ajaya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ajaya/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ajaya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ajaya/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ajaya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ajaya/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
x = np.zeros(10)
print (x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print("Size of the array: ", x.size)
  
print("Memory size of one array element in bytes: ", x.itemsize)
  

print("Memory size of numpy array in bytes:", x.size * x.itemsize)

Size of the array:  10
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-6-1663cd30cb7c>, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
y = np.zeros(10)
y[4]=1
print (y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
print("Reverse array:")
z = z[::-1]
print(z)


Reverse array:
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
p=np.arange(0,9)
p=p.reshape(3,3)
print (p)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
q = np.nonzero([1,2,0,0,4,0])
print(q)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
m=np.identity(3)
print('3x3 matrix:')
print(m)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
x = np.random.random((3,3,3))
print(x)

[[[0.10658647 0.68165395 0.91662108]
  [0.13536377 0.60012151 0.82460013]
  [0.19506456 0.6871393  0.46899861]]

 [[0.93751078 0.10869311 0.29944208]
  [0.36057902 0.90810127 0.35478252]
  [0.5466819  0.84872855 0.67774945]]

 [[0.25237354 0.08084768 0.33109038]
  [0.04677975 0.27195461 0.63499552]
  [0.47343647 0.25187332 0.93181944]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
x = np.random.random((10,10))
print(x)
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[0.94613211 0.82184353 0.9700244  0.64168253 0.72243494 0.702119
  0.66160975 0.27724123 0.57047007 0.28298764]
 [0.17463593 0.92472869 0.42197248 0.21358144 0.29385693 0.961609
  0.93712572 0.29695889 0.67160366 0.01187188]
 [0.00975381 0.92568126 0.91203516 0.41688967 0.17874285 0.87926862
  0.2838177  0.21165068 0.95243264 0.00864175]
 [0.86285698 0.57722053 0.46266491 0.89147177 0.50632033 0.40143564
  0.2315501  0.16668524 0.92397388 0.19841571]
 [0.28781701 0.22947795 0.69049528 0.51170612 0.28333269 0.4485309
  0.89042397 0.88666055 0.13703088 0.08024314]
 [0.29453088 0.68357999 0.37041798 0.40111819 0.97305853 0.25239275
  0.81489715 0.24116404 0.51400704 0.35240892]
 [0.92831276 0.96340078 0.92185309 0.76649953 0.76434586 0.74813015
  0.30264305 0.79902768 0.59488425 0.87860077]
 [0.92045257 0.67974218 0.95303895 0.55753551 0.38039012 0.53769317
  0.67905129 0.35884799 0.21216994 0.46412649]
 [0.10512607 0.27818889 0.01446788 0.81390235 0.13816129 0.43015041
  0.61678815 0.42

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
x = np.random.random(30)
print("Mean Value:",x.mean())

Mean Value: 0.4831059034190366


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
x = np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [32]:
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [41]:
a= 0 * np.nan
b= np.nan == np.nan
c= np.inf > np.nan
d= np.nan - np.nan
e= np.nan in set([np.nan])
f= 0.3 == 3 * 0.1
print(a,b,c,d,e,f)

nan False False nan True False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [43]:
x = np.diag(np.arange(1,5),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [45]:
x = np.ones ((8,8), dtype=int)
x[1::2, ::2]= 0
x[::2, 1::2] = 0
print (x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [46]:
print(np.unravel_index(100,(6,7,8)))

#Number of elements= 6*7*8
#100= 1. (7*8) + 5. (8) + 4. 1 
# so the index is (1,5,4)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [47]:
array= np.array([[1,0], [0,1]])
x = np.tile(array,(4,4))
print (x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [48]:
x= np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.52736997 0.52956495 0.9416287  0.03245466 0.98491433]
 [0.88023438 0.67376438 0.29013328 0.31263437 0.83591847]
 [1.         0.61178987 0.         0.38513101 0.17607841]
 [0.2473196  0.94961749 0.31176451 0.56336219 0.13156277]
 [0.44466324 0.9543832  0.22636041 0.86942315 0.55486298]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [57]:
color = np.dtype([("r", 'B'),
                  ("g", 'B'),
                  ("b", 'B'),
                  ("a", 'B')])
#B for unsigned bytes

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [50]:
x= np.arange(15).reshape(5,3)
y= np.arange(6).reshape(3,2)
print (x)
print (y)
print("Product:", np.dot(x,y))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
Product: [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [59]:
x = np.arange(15)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#It Showed 9 10 when I ran it for first time, but i ran it once again, it showed 10 10. but now again 9 10 .. God or wat :)

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [85]:
print(Z**Z)
#2 << Z >> 2
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z

invalid expressions are used as comments

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [87]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-87-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-87-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [91]:
x= np.random.uniform(-5,5,5).round()
print(x)

[ 4. -4. -1.  1. -0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [92]:
x = np.random.randint(0,10,5)
y = np.random.randint(0,10,7)
print(np.intersect1d(x,y))

[4 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [99]:
old_settings = np.seterr(all='ignore')  #seterr to known value
print(np.seterr(over='raise'))
print(np.seterr(**old_settings)) # reset to default

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}
{'divide': 'ignore', 'over': 'raise', 'under': 'ignore', 'invalid': 'ignore'}


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [100]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [101]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-08-29
Today:  2021-08-30
Tomorrow:  2021-08-31


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [104]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [106]:
A = np.ones(3)*1
B = np.ones(3)*1
np.add(A,B,out=B) # stores A+B value in B
np.divide(A,2,out=A) #stores A/2 value in A
np.negative(A,out=A) #stores -A value in A
np.multiply(A,B,out=A) # Now our updated A =-A/2 and B= A+B , now multiply

array([-1., -1., -1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [109]:
x = np.random.uniform(0,10,10)

print (x - x%1)
print (np.floor(x))
print (np.ceil(x)-1)
print (x.astype(int))
print (np.trunc(x))

[2. 9. 8. 8. 6. 8. 5. 6. 2. 1.]
[2. 9. 8. 8. 6. 8. 5. 6. 2. 1.]
[2. 9. 8. 8. 6. 8. 5. 6. 2. 1.]
[2 9 8 8 6 8 5 6 2 1]
[2. 9. 8. 8. 6. 8. 5. 6. 2. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [108]:
x=np.arange(25).reshape(5,5)
x[:,:]=np.arange(5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [107]:
def generate():
   for n in range(10):
       yield n
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [110]:
x = np.linspace(0,1,10,endpoint=False)[1:-1]
print(x)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [117]:
x=np.random.random(15)
print(x)

[0.16582481 0.45771089 0.44948395 0.92076578 0.99329702 0.56794444
 0.75105742 0.73012605 0.26000066 0.6318063  0.37891953 0.22460531
 0.57648185 0.80674132 0.80402593]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [119]:
x = np.arange(8)
np.add.reduce(x)

28

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [121]:
x = np.random.randint(0,2,6)
print(x)
y = np.random.randint(0,2,6)
print(y)
equal = np.allclose(x, y)
print(equal)

[1 0 0 0 0 1]
[0 0 0 1 0 1]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [122]:
x = np.zeros(10)
x.flags.writeable = False
print("Try to change the value of the first element:")
x[0] = 1

Try to change the value of the first element:


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [124]:
z= np.random.random((10,2))
x = z[:,0]
y = z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)

print(r)
print(t)

[0.41578291 0.62518579 1.05595336 0.59513303 1.10577709 0.60555547
 0.79458886 0.64621748 0.61105556 0.81055146]
[1.00663861 1.36221593 1.22492754 0.61014158 0.94032906 1.28637768
 0.46301178 0.32178237 0.43986179 0.1187127 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [125]:
x=np.random.random(10)
print(x)
x[x.argmax()] = -1
print(x)

[0.05731478 0.93033975 0.35552087 0.89582205 0.80071265 0.09740378
 0.98235333 0.9691876  0.81856274 0.86474752]
[ 0.05731478  0.93033975  0.35552087  0.89582205  0.80071265  0.09740378
 -1.          0.9691876   0.81856274  0.86474752]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [130]:
Z = np.zeros((6,6), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,6), np.linspace(0,1,6))
print(Z)

[[(0. , 0. ) (0.2, 0. ) (0.4, 0. ) (0.6, 0. ) (0.8, 0. ) (1. , 0. )]
 [(0. , 0.2) (0.2, 0.2) (0.4, 0.2) (0.6, 0.2) (0.8, 0.2) (1. , 0.2)]
 [(0. , 0.4) (0.2, 0.4) (0.4, 0.4) (0.6, 0.4) (0.8, 0.4) (1. , 0.4)]
 [(0. , 0.6) (0.2, 0.6) (0.4, 0.6) (0.6, 0.6) (0.8, 0.6) (1. , 0.6)]
 [(0. , 0.8) (0.2, 0.8) (0.4, 0.8) (0.6, 0.8) (0.8, 0.8) (1. , 0.8)]
 [(0. , 1. ) (0.2, 1. ) (0.4, 1. ) (0.6, 1. ) (0.8, 1. ) (1. , 1. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [132]:
x = np.arange(5)
print(x)
y = y + 0.5
print(y)

x=x.reshape(-1,1)
d=x-y

c=1.0/d

print(c)

[0 1 2 3 4]
[1.35135289 1.61163543 1.99342115 1.34100141 1.8931938  1.58122724
 1.35489898 1.20437141 1.26019626 1.09599691]
[[ -0.73999916  -0.62048772  -0.50165014  -0.74571137  -0.52820794
   -0.63242017  -0.7380624   -0.83030865  -0.79352719  -0.91241133]
 [ -2.84614137  -1.63496088  -1.00662242  -2.93253923  -1.11957785
   -1.72049747  -2.81770321  -4.89305219  -3.84325274 -10.41700223]
 [  1.54167033   2.57490017 152.00226487   1.51745392   9.36275263
    2.38792992   1.55014482   1.25686786   1.35170985   1.10619091]
 [  0.60655794   0.72027191   0.99346415   0.60277327   0.90350054
    0.70483451   0.60786541   0.55690804   0.57477748   0.52520923]
 [  0.37755124   0.41869655   0.49836068   0.37608143   0.47465211
    0.4134328    0.37805739   0.35770131   0.36498965   0.34435225]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [134]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   #print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [143]:
#np.set_printoptions(threshold=np.nan)
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [144]:
x = np.arange(10)
print(x)
a = np.random.uniform(0,10)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin() #retruns the index of min value of absolute value of x-a
print(x[index])

[0 1 2 3 4 5 6 7 8 9]
Value to compare:
3.1828137842626814
3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [30]:
R = np.ones(4, [ ('position', [ ('x', float),('y', float)]), ('color',    [ ('r', float), ('g', float), ('b', float)])])
print(R)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [26]:
a= np.random.random((100,2)) #random numbers
x,y = np.atleast_2d(a[:,0], a[:,1]) #views input as arrays with atleast 2-dimension
#print(x)
#print(x.T)
#print(x-x.T)
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.22770266 0.56874279 ... 0.90430689 0.73055233 1.02663627]
 [0.22770266 0.         0.55577236 ... 0.77111571 0.50301731 0.90559171]
 [0.56874279 0.55577236 0.         ... 0.47432051 0.78649201 0.5486319 ]
 ...
 [0.90430689 0.77111571 0.47432051 ... 0.         0.6620536  0.14142919]
 [0.73055233 0.50301731 0.78649201 ... 0.6620536  0.         0.7960013 ]
 [1.02663627 0.90559171 0.5486319  ... 0.14142919 0.7960013  0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [9]:
Z = np.random.uniform(0,10,10).astype(np.float32)
print(Z)
Z = Z.astype(np.int32)
print(Z)

[6.560324   0.16010039 2.826978   9.6359825  6.3430686  6.2352343
 1.2508746  9.049433   9.461208   5.4944773 ]
[6 0 2 9 6 6 1 9 9 5]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [37]:
from io import StringIO
file_name = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11''')
Z = np.genfromtxt(file_name, delimiter=",")
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [39]:
z = np.arange(9).reshape(3,3)
print(z)
y=np.ndenumerate(z)
print(y)
for index, value in y:
    print(index, value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [41]:
x, y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("2D Gaussian-like array:")
print(g)

2D Gaussian-like array:
[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [43]:

p = 3
Z = np.ones((10,10))
np.put(Z, np.random.choice(range(10*10), p, replace=False),0)
print (Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [47]:

X = np.random.rand(3, 3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.2020502  0.73923416 0.12867925]
 [0.40867064 0.18963761 0.81416837]
 [0.1331536  0.71954425 0.7434019 ]]

Subtract the mean of each row of the said matrix:

[[-0.15460434  0.38257963 -0.22797528]
 [-0.0621549  -0.28118793  0.34334283]
 [-0.39887965  0.187511    0.21136865]]


#### 59. How to sort an array by the nth column? (★★☆)

In [49]:
a=  np.array([[9, 2, 3],[4, 5, 6],[7, 0, 5]])
print(a)
a = a[a[:,1].argsort()] 
print(a)

[[9 2 3]
 [4 5 6]
 [7 0 5]]
[[7 0 5]
 [9 2 3]
 [4 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [50]:
nums = np.random.randint(0,3,(4,10))
print(nums)
print("\nTest whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())

[[0 0 2 1 0 2 2 0 0 0]
 [2 0 1 1 1 2 0 2 0 0]
 [0 2 1 1 2 0 1 0 1 0]
 [1 1 0 2 1 0 0 2 0 2]]

Test whether the said array has null columns or not:
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [51]:
x = np.random.uniform(1, 12, 5) #random array
v = 3 #let given value
n = x.flat[np.abs(x - v).argmin()]
print(n)

3.4158945188019167


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [53]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
print(A)
print(B)
print(it)
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [64]:
class myClass(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

Z = myClass(np.arange(10), "AJay")
print (Z.name)

AJay


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [38]:
X = np.ones(10)#vector for adding 1
print(X)
I = np.random.randint(0,len(Z),20)
print(I)
Y= np.bincount(I, minlength=len(Z))#retruns the no. of appearance of each value in array of non negative ints
print(Y)#this will be our second vector
X+=Y
print(X)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2 2 6 7 6 3 7 5 7 7 5 6 0 5 9 4 3 5 1 6]
[1 1 2 2 1 4 4 4 0 1]
[2. 2. 3. 3. 2. 5. 5. 5. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [40]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
G=np.bincount(I,X)
print(G)
F = np.bincount(I,weights=X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]
[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [35]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [34]:
A = np.random.randint(0,5,(3,4,3,4))
print(A)
sum = A.sum(axis=(-2,-1))
print(sum)

[[[[2 3 3 1]
   [1 2 4 1]
   [1 1 0 3]]

  [[2 1 4 2]
   [2 2 2 1]
   [0 4 3 0]]

  [[1 2 1 1]
   [4 0 2 3]
   [2 2 4 2]]

  [[4 1 1 0]
   [1 3 0 4]
   [3 2 4 4]]]


 [[[2 2 0 3]
   [1 2 1 0]
   [0 4 2 3]]

  [[4 2 4 1]
   [3 3 4 4]
   [4 4 0 1]]

  [[4 1 3 0]
   [1 1 0 1]
   [3 4 4 4]]

  [[1 4 1 0]
   [4 1 4 2]
   [3 2 2 1]]]


 [[[4 2 3 3]
   [1 3 4 0]
   [4 2 4 0]]

  [[2 0 3 1]
   [2 4 2 0]
   [2 1 3 1]]

  [[4 0 0 1]
   [0 2 4 3]
   [1 1 0 4]]

  [[4 0 1 3]
   [1 3 2 1]
   [2 0 0 4]]]]
[[22 23 24 27]
 [20 34 26 25]
 [30 21 20 21]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [41]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)#for sum
D_counts = np.bincount(S)#for total count
D_means = D_sums / D_counts #for mean
print(D_means)


[0.60601525 0.54963917 0.48532777 0.54251673 0.5601516  0.51707442
 0.62510038 0.5188795  0.53903124 0.45418611]


#### 69. How to get the diagonal of a dot product? (★★★)

In [20]:
a = np.random.rand(6,3)
print(a)
b = np.random.rand(3,3)
print(b)
print(np.diag(np.dot(a, b)))


[[0.71038384 0.17857655 0.55711648]
 [0.42699258 0.09435598 0.13187998]
 [0.50143135 0.69522095 0.29418162]
 [0.96065342 0.94678028 0.81459753]
 [0.75546766 0.93560631 0.98867748]
 [0.14125188 0.23982489 0.26554874]]
[[0.49702457 0.15285457 0.68118156]
 [0.1619419  0.94931522 0.60150543]
 [0.22667403 0.91937077 0.97089777]]
[0.50828108 0.27608793 1.04536524]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [12]:
Z = np.array([1,2,3,4,5])
n = 3 #no. of consecutive zeros
Z0 = np.zeros(len(Z) + (len(Z)-1)*(n))
print(Z0)
for i in range(len(Z0)):
    if i%4==0:
        Z0[i]=Z[i//4]

print(Z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [8]:
A = np.ones((5,5,3))
print(A)
B = np.zeros((5,5))
print(B)
print(A * B[:,:,None])#for valid multiplication we have changed the shape of B

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


#### 72. How to swap two rows of an array? (★★★)

In [2]:
a = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) #define an array
print(a)

a[[0, 2]] = a[[2, 0]]#swap two rows
print(a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [64]:
A = np.random.randint(0,20,(10,3))
print(A)
B=A.repeat(2,axis=1)
print(B)
F = np.roll(B,-1,axis=1)
print(F)
F = F.reshape(len(F)*3,2)
print(F)
F = np.sort(F,axis=1)
print(F)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

#Understood the funcions, but why would this give the required result?? No idea :(

[[11 16  9]
 [ 6 18  8]
 [ 3 13  4]
 [13  3 17]
 [16  9  0]
 [17 15  7]
 [12  9 16]
 [19  1  7]
 [18 12  5]
 [11 12 19]]
[[11 11 16 16  9  9]
 [ 6  6 18 18  8  8]
 [ 3  3 13 13  4  4]
 [13 13  3  3 17 17]
 [16 16  9  9  0  0]
 [17 17 15 15  7  7]
 [12 12  9  9 16 16]
 [19 19  1  1  7  7]
 [18 18 12 12  5  5]
 [11 11 12 12 19 19]]
[[11 16 16  9  9 11]
 [ 6 18 18  8  8  6]
 [ 3 13 13  4  4  3]
 [13  3  3 17 17 13]
 [16  9  9  0  0 16]
 [17 15 15  7  7 17]
 [12  9  9 16 16 12]
 [19  1  1  7  7 19]
 [18 12 12  5  5 18]
 [11 12 12 19 19 11]]
[[11 16]
 [16  9]
 [ 9 11]
 [ 6 18]
 [18  8]
 [ 8  6]
 [ 3 13]
 [13  4]
 [ 4  3]
 [13  3]
 [ 3 17]
 [17 13]
 [16  9]
 [ 9  0]
 [ 0 16]
 [17 15]
 [15  7]
 [ 7 17]
 [12  9]
 [ 9 16]
 [16 12]
 [19  1]
 [ 1  7]
 [ 7 19]
 [18 12]
 [12  5]
 [ 5 18]
 [11 12]
 [12 19]
 [19 11]]
[[11 16]
 [ 9 16]
 [ 9 11]
 [ 6 18]
 [ 8 18]
 [ 6  8]
 [ 3 13]
 [ 4 13]
 [ 3  4]
 [ 3 13]
 [ 3 17]
 [13 17]
 [ 9 16]
 [ 0  9]
 [ 0 16]
 [15 17]
 [ 7 15]
 [ 7 17]
 [ 9 12]
 [ 9 16]
 [12 1

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [48]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.arange(len(C))
print(A)
B=np.repeat(A,C)#repeats values of A as many times as C, i.e 0 times 0, 2 times 1, 1 time 2 and so on..
print(B)

[0 2 1 1 2 0 1]
[0 1 2 3 4 5 6]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [55]:
def average(a, n=3) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n
Z = np.arange(10)
print(Z)
print(average(Z))

[0 1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)